### ISSUE TITLE
Failed to load skill data from Guild Wars 2 API

### ISSUE THREAD

**Issue by NotAreki** [xvwyh/BuildPad#10]
It says "Some functionality is disabled" in the error but pretty much nothing is working as of a recent patch.

I'm running the 2021-10-27 version and I have tried deleting the \addons\arcdps\arcdps.buildpad\rendercache\ folder as suggested on the BuildPad website. The issue exists not only for me, but for other players as well.

![unknown](https://user-images.githubusercontent.com/101595577/187045372-abe57c09-b475-4b5e-bffe-6e4eee4413a5.png)

**Comment by xvwyh** [comment]
Do the following links open in your browser?

https://api.guildwars2.com/v2/professions?lang=en&v=2019-12-19T00:00:00.000Z&ids=all
https://api.guildwars2.com/v2/legends?lang=en&v=2019-12-19T00:00:00.000Z&ids=all
https://buildpad.gw2archive.eu/skillpalette.json
https://buildpad.gw2archive.eu/pets.json
https://buildpad.gw2archive.eu/itemstatsicons.json
https://buildpad.gw2archive.eu/apifallback_legends.json
https://buildpad.gw2archive.eu/apifallback_professions.json

**Comment by NotAreki** [comment]
Yup. All of them open correctly.

**Comment by xvwyh** [comment]
Then, frankly, I have no idea. Maybe something is blocking specifically your game client from accessing these urls. The only thing that can cause that error to appear is if buildpad fails to load any of these links or fails to parse the data from them, but if it was latter - I should be having the problem too, but I'm not.

I don't suppose you happen to be using VPNs/proxies to access websites?
