### ISSUE TITLE
Weapon icons are gone after switching api language

### ISSUE THREAD

**Issue by ForgottenR** [xvwyh/BuildPad#16]
**Describe the bug**
After switching api languages, weapons icons are gone. It seems like a visual bug since we can still blindly edit builds and the weapons in the chat link shown in game is affected.

**To Reproduce**
1. Switch the api language
2. take a look at a build saved with weapon, or try to edit weapons in the addon. 

**Expected behavior**
show the weapon icon
**Screenshots**
![image](https://github.com/user-attachments/assets/4588ca5d-2bac-4a6c-a6d8-58b5afcbad9d)

**Comment by xvwyh** [comment]
Fixed in https://github.com/xvwyh/BuildPad/commit/6d4db9276262830c04c505ec6b573f47b606ae64
