### ISSUE TITLE
Game remains open in background

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [xvwyh/BuildPad#8]
So this is a previous bug, but after the most recent update my gw2-64.exe remains running in the background after exiting the game.  And this only happens with BuildPad enabled.

**Comment by xvwyh** [comment]
Can't reproduce, the game closes just fine for me.
Can you click on all these links and verify that all of them are opening for you in a browser?
https://buildpad.gw2archive.eu/skillpalette.json
https://buildpad.gw2archive.eu/apifallback_legends.json
https://buildpad.gw2archive.eu/apifallback_professions.json
https://api.guildwars2.com/v2/professions?lang=en&v=2019-12-19T00:00:00.000Z&ids=Guardian,Warrior,Engineer
https://api.guildwars2.com/v2/specializations?lang=en&v=2019-12-19T00:00:00.000Z&ids=1,2,3
https://api.guildwars2.com/v2/traits?lang=en&v=2019-12-19T00:00:00.000Z&ids=214,221,222
https://api.guildwars2.com/v2/skills?lang=en&v=2019-12-19T00:00:00.000Z&ids=1110,1115,1118
https://api.guildwars2.com/v2/items?lang=en&v=2019-12-19T00:00:00.000Z&ids=6,15,24
https://api.guildwars2.com/v2/itemstats?lang=en&v=2019-12-19T00:00:00.000Z&ids=50,112,137
https://api.guildwars2.com/v2/pets?lang=en&v=2019-12-19T00:00:00.000Z&ids=1,2,3
https://api.guildwars2.com/v2/legends?lang=en&v=2019-12-19T00:00:00.000Z&ids=Legend1,Legend2,Legend3
https://render.guildwars2.com/file/CC2E01E0F566A6EEF4F2EC2B19AA7A3E1FEFB1B4/60984.png

**Comment by SaiyanOfDarkness** [comment]
I checked all of them.. but this one.. https://api.guildwars2.com/v2/legends?lang=en&v=2019-12-19T00:00:00.000Z&ids=1,2,3

came up with..

    {
      "text": "all ids provided are invalid"
    }

**Edit:**  Oh wait you edited the link after I got the email.. yeah that one works fine too.

**Comment by xvwyh** [comment]
Is BuildPad even working for you, then? Does the window show up, are the icons in tooltips loading?
